{
  "formatVersion": "1.1",
  "component": {
    "group": "com.awakenmobile",
    "module": "awakensdk-debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "awakensdk-debug-1.0.aar",
          "url": "awakensdk-debug-1.0.aar",
          "size": 994574,
          "sha512": "a6c36d582f92fbd63ee65a41a68d94881cdc284e6d3cec5b05f8d76c3dc73b4622fa57bd26625b8fe33a322d05f072e133a6076e0cdcece597418ed67b35cae2",
          "sha256": "4b08195cb20fd6810d4fccaa05d25194da48ecea324157a1694156faa5d47201",
          "sha1": "9c03599211eda3fa10f8a46158d90af8e327eee5",
          "md5": "ee872763147261a30315a832e525b47f"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.ads",
          "module": "ads-identifier",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-core",
          "version": {
            "requires": "2.74.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-sns",
          "version": {
            "requires": "2.74.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "awakensdk-debug-1.0.aar",
          "url": "awakensdk-debug-1.0.aar",
          "size": 994574,
          "sha512": "a6c36d582f92fbd63ee65a41a68d94881cdc284e6d3cec5b05f8d76c3dc73b4622fa57bd26625b8fe33a322d05f072e133a6076e0cdcece597418ed67b35cae2",
          "sha256": "4b08195cb20fd6810d4fccaa05d25194da48ecea324157a1694156faa5d47201",
          "sha1": "9c03599211eda3fa10f8a46158d90af8e327eee5",
          "md5": "ee872763147261a30315a832e525b47f"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "awakensdk-debug-1.0-sources.jar",
          "url": "awakensdk-debug-1.0-sources.jar",
          "size": 131021,
          "sha512": "a54bc5d7c57f7ae0a5577fdde3ec3cd118a08cb54734588d47655b0953cbdd73854c239df9aa799817e086d0301629d729ef3911f2a76fb8bd0a227378ea1187",
          "sha256": "4fb9e6d5c373f9adb9e9eef6ccb5328d6ffc24a99eac4ef4da6b4e09ef8cf6e8",
          "sha1": "582b4bbc7ca9a3bc8dd998dc761d403e99479397",
          "md5": "c5b72d1230fe8aa956c9c3729bfa4f02"
        }
      ]
    }
  ]
}
