{
  "formatVersion": "1.1",
  "component": {
    "group": "com.awakenmobile",
    "module": "awakensdk-release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "awakensdk-release-1.0.aar",
          "url": "awakensdk-release-1.0.aar",
          "size": 1089578,
          "sha512": "644245683d67f8a4f4491258911a8a13d503f00445c3c8ca2cac37a67a0fd6eff7c918e13562f24517adc9e763c0a38650cbd88400d19defdc239f4d18b0416a",
          "sha256": "f38982e6a71abc30031c8da0f2286de6e75843156431510ccd0dff2829f53dab",
          "sha1": "7226e1fb240b2ce56a52f1d4eef851160213e082",
          "md5": "fa678aa9731f966bbb199959b7dc7e2e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.ads",
          "module": "ads-identifier",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-core",
          "version": {
            "requires": "2.74.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-sns",
          "version": {
            "requires": "2.74.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "awakensdk-release-1.0.aar",
          "url": "awakensdk-release-1.0.aar",
          "size": 1089578,
          "sha512": "644245683d67f8a4f4491258911a8a13d503f00445c3c8ca2cac37a67a0fd6eff7c918e13562f24517adc9e763c0a38650cbd88400d19defdc239f4d18b0416a",
          "sha256": "f38982e6a71abc30031c8da0f2286de6e75843156431510ccd0dff2829f53dab",
          "sha1": "7226e1fb240b2ce56a52f1d4eef851160213e082",
          "md5": "fa678aa9731f966bbb199959b7dc7e2e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "awakensdk-release-1.0-sources.jar",
          "url": "awakensdk-release-1.0-sources.jar",
          "size": 150837,
          "sha512": "f8729369bec9c6c2501de66d88547d69ff44dc7af52a8b52f888f9293769ba9ef166c529ee42b7180a673a7a4b6a9b42dc20ffb282677333d45ca1fe7eaec624",
          "sha256": "f6c301cbcae626e454d8bc2c1cec91d00d3755e2c6847f25ca60cbb8e5a406c6",
          "sha1": "8f033ec0f13a2dd1dcce6985e0f05f0ea48afc9e",
          "md5": "e3b180ac14af523f5927469476c925a9"
        }
      ]
    }
  ]
}
